SELECT 'mx' AS tablename, 'MAX SERVICE_DATE LATEST' AS TEST, MAX(service_date)::VARCHAR AS RESULT
FROM {{DB}}.{{SCHEMA}}.MEDICAL_EVENTS_REVIEW_LATEST
UNION ALL
SELECT 'mx', 'MAX SERVICE_DATE PREVIOUS', MAX(service_date)::VARCHAR
FROM {{DB}}.{{SCHEMA}}.MEDICAL_EVENTS_LATEST
UNION ALL
SELECT 'rx', 'MAX FILL_DATE LATEST', MAX(fill_date)::VARCHAR
FROM {{DB}}.{{SCHEMA}}.PHARMACY_EVENTS_REVIEW_LATEST
UNION ALL
SELECT 'rx', 'MAX FILL_DATE PREVIOUS', MAX(fill_date)::VARCHAR
FROM {{DB}}.{{SCHEMA}}.PHARMACY_EVENTS_LATEST;