SELECT 'MAX INPATIENT DATE LATEST' AS TEST,
       MAX(COALESCE(claim_through_date, discharge_date, claim_from_date, admit_date))::VARCHAR AS RESULT
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.INPATIENT_EVENTS_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX INPATIENT DATE PREVIOUS',
       MAX(COALESCE(claim_through_date, discharge_date, claim_from_date, admit_date))::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.INPATIENT_EVENTS_{{LATEST_SUFFIX}}')
UNION ALL
SELECT 'MAX NON_INPATIENT SERVICE_DATE LATEST',
       MAX(service_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.NON_INPATIENT_EVENTS_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX NON_INPATIENT SERVICE_DATE PREVIOUS',
       MAX(service_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.NON_INPATIENT_EVENTS_{{LATEST_SUFFIX}}')
UNION ALL
SELECT 'MAX RX FILL_DATE LATEST',
       MAX(fill_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.PHARMACY_EVENTS_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX RX FILL_DATE PREVIOUS',
       MAX(fill_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.PHARMACY_EVENTS_{{LATEST_SUFFIX}}');