SELECT 'MAX SERVICE_DATE LATEST' AS TEST,
       MAX(service_date)::VARCHAR AS RESULT
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.MEDICAL_EVENTS_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX SERVICE_DATE PREVIOUS',
       MAX(service_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.MEDICAL_EVENTS_{{LATEST_SUFFIX}}')
UNION ALL
SELECT 'MAX FILL_DATE LATEST',
       MAX(fill_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.PHARMACY_EVENTS_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX FILL_DATE PREVIOUS',
       MAX(fill_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.PHARMACY_EVENTS_{{LATEST_SUFFIX}}');
