SELECT 'MAX SERVICE_LINE DATE (LATEST)' AS TEST,
       MAX(COALESCE(service_to, service_from, date_of_service))::VARCHAR AS RESULT
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.MEDICAL_SERVICE_LINES_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX SERVICE_LINE DATE (PREVIOUS)',
       MAX(COALESCE(service_to, service_from, date_of_service))::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.MEDICAL_SERVICE_LINES_{{LATEST_SUFFIX}}')
UNION ALL
SELECT 'MAX RX FILL_DATE (LATEST)',
       MAX(fill_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.PHARMACY_{{REVIEW_SUFFIX}}')
UNION ALL
SELECT 'MAX RX FILL_DATE (PREVIOUS)',
       MAX(fill_date)::VARCHAR
FROM IDENTIFIER('{{DB}}.{{SCHEMA}}.PHARMACY_{{LATEST_SUFFIX}}');